import { BaseEntity, Column, Entity } from '@neogroup/neorm'

@Entity({ table: 'organizations' })
export class Organization extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  /** Subdomain slug used to identify the organization (e.g. "club-aleman"). */
  @Column()
  domainName!: string

  /** When true, users can self-register with the "organizer" role. When false, all self-registered users become players. */
  @Column()
  allowOrganizersCreation!: boolean

  @Column({ cast: 'date' })
  createdAt!: Date
}
