import { BaseEntity, Column, Entity } from '@neogroup/neorm'

@Entity({ table: 'organizations' })
export class Organization extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  /** Subdomain slug used to identify the organization (e.g. "club-aleman"). */
  @Column()
  domainName!: string

  /** When true, users can self-register with the "organizer" role. When false, all self-registered users become players. */
  @Column()
  allowOrganizersCreation!: boolean

  /**
   * IANA timezone of the organization (e.g. "America/Argentina/Buenos_Aires").
   * Used to interpret a tournament's startDate/startTime so the processTournaments
   * cron starts each tournament at the organization's local scheduled time.
   */
  @Column()
  timezone!: string

  @Column({ cast: 'date' })
  createdAt!: Date
}
