import { BaseEntity, Column, Entity } from '@neogroup/neorm'

@Entity({ table: 'password_reset_tokens' })
export class PasswordResetToken extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  userId!: number

  @Column()
  token!: string

  @Column({ cast: 'date' })
  expiresAt!: Date

  @Column({ cast: 'date' })
  createdAt!: Date
}
