import { BaseEntity, Column, Entity, Serializable } from '@neogroup/neorm'
import { Role } from '@/app/(auth)/models/Role'
import { getUserDisplayName } from '@/app/(auth)/utils/user'
import { OrganizationScope } from '@/app/models/OrganizationScope'
import { getGravatarUrl } from '@/app/utils/gravatar'

@Entity({ table: 'users' })
export class User extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  organizationId!: number

  @Column()
  email!: string

  @Column()
  passwordHash!: string | null

  @Column()
  firstName!: string | null

  @Column()
  lastName!: string | null

  @Column()
  nickname!: string | null

  @Column()
  phoneNumber!: string | null

  /** Role of the user: 1 = organizer, 2 = player. Assigned once, cannot be switched. */
  @Column()
  roleId!: Role | null

  /** True when the user verified their email address. Always true for Google-authenticated users. */
  @Column({ cast: 'boolean' })
  emailVerified!: boolean

  @Column({ cast: 'date' })
  createdAt!: Date

  @Serializable()
  get displayName(): string {
    return getUserDisplayName(this)
  }

  @Serializable()
  get avatarUrl(): string {
    return getGravatarUrl(this.email, 80)
  }

  protected static booted(): void {
    User.addGlobalScope(new OrganizationScope())
  }
}
