import { Column, Entity } from '@neogroup/neorm'

@Entity({ table: 'competitors' })
export class Competitor {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournament_id!: number

  /** Platform user that registered this entry (null when added manually). */
  @Column()
  user_id!: number | null

  /** Partner as a platform user (doubles disciplines only). */
  @Column()
  partner_user_id!: number | null

  /** Partner as free text (doubles disciplines only). */
  @Column()
  partner_name!: string | null

  /** Resolved name shown everywhere (player or "Player / Partner"). */
  @Column()
  display_name!: string

  @Column({ cast: 'date' })
  created_at!: Date
}

/** Typed facade for the static query methods injected by the @Entity decorator. */
export const CompetitorModel = Competitor as any
