import { BaseEntity, Column, Entity } from '@neogroup/neorm'

@Entity({ table: 'competitors' })
export class Competitor extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentId!: number

  /** Platform user that registered this entry (null when added manually). */
  @Column()
  userId!: number | null

  /** Partner as a platform user (doubles disciplines only). */
  @Column()
  partnerUserId!: number | null

  /** Partner as free text (doubles disciplines only). */
  @Column()
  partnerName!: string | null

  /** Resolved name shown everywhere (player or "Player / Partner"). */
  @Column()
  displayName!: string

  @Column({ cast: 'date' })
  createdAt!: Date
}
