import { Column, Entity } from '@neogroup/neorm'

import { MatchScore, MatchSide, MatchStatus } from '@/app/_models/types'

@Entity({ table: 'matches' })
export class Match {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournament_id!: number

  @Column({ cast: 'number' })
  round_id!: number

  /** Ordering inside the round; also encodes the playoff bracket slot. */
  @Column({ cast: 'number' })
  position!: number

  /**
   * Competitor ids on each side. A side holds a single id except in
   * americano tournaments with partner swapping, where two individual
   * competitors team up per round. `away_competitor_ids` is null for byes.
   */
  @Column({ cast: 'json' })
  home_competitor_ids!: number[]

  @Column({ cast: 'json' })
  away_competitor_ids!: number[] | null

  @Column({ cast: 'json' })
  score!: MatchScore | null

  @Column()
  status!: MatchStatus

  @Column()
  winner!: MatchSide | null

  @Column({ cast: 'date' })
  created_at!: Date

  @Column({ cast: 'date' })
  updated_at!: Date
}

/** Typed facade for the static query methods injected by the @Entity decorator. */
export const MatchModel = Match as any
