import { Column, Entity } from '@neogroup/neorm'

import { RoundStatus } from '@/app/_models/types'

@Entity({ table: 'rounds' })
export class Round {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournament_id!: number

  @Column({ cast: 'number' })
  number!: number

  @Column()
  status!: RoundStatus

  @Column({ cast: 'date' })
  created_at!: Date
}

/** Typed facade for the static query methods injected by the @Entity decorator. */
export const RoundModel = Round as any
