import { BaseEntity, Column, Entity } from '@neogroup/neorm'
import { RoundStatus } from '@/app/_models/types'

@Entity({ table: 'rounds' })
export class Round extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentId!: number

  @Column({ cast: 'number' })
  number!: number

  @Column()
  status!: RoundStatus

  @Column({ cast: 'date' })
  createdAt!: Date
}
