import { BaseEntity, Column, Entity } from '@neogroup/neorm'
import { Discipline, ScoreFormat, TournamentSettings, TournamentStatus, TournamentType } from '@/app/_models/types'

@Entity({ table: 'tournaments' })
export class Tournament extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  ownerId!: number

  @Column()
  name!: string

  @Column()
  description!: string | null

  @Column()
  status!: TournamentStatus

  @Column()
  discipline!: Discipline

  @Column()
  type!: TournamentType

  @Column()
  scoreFormat!: ScoreFormat

  @Column()
  startDate!: string

  @Column()
  location!: string | null

  @Column({ cast: 'number' })
  maxCompetitors!: number

  @Column({ cast: 'json' })
  settings!: TournamentSettings | null

  @Column({ cast: 'number' })
  currentRound!: number

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date
}
