import { Column, Entity } from '@neogroup/neorm'
import { Discipline, ScoreFormat, TournamentSettings, TournamentStatus, TournamentType } from '@/app/_models/types'

@Entity({ table: 'tournaments' })
export class Tournament {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  owner_id!: number

  @Column()
  name!: string

  @Column()
  description!: string | null

  @Column()
  status!: TournamentStatus

  @Column()
  discipline!: Discipline

  @Column()
  type!: TournamentType

  @Column()
  score_format!: ScoreFormat

  @Column()
  start_date!: string

  @Column()
  location!: string | null

  @Column({ cast: 'number' })
  max_competitors!: number

  @Column({ cast: 'json' })
  settings!: TournamentSettings | null

  @Column({ cast: 'number' })
  current_round!: number

  @Column({ cast: 'date' })
  created_at!: Date

  @Column({ cast: 'date' })
  updated_at!: Date
}

/** Typed facade for the static query methods injected by the @Entity decorator. */
export const TournamentModel = Tournament as any
