import { Column, Entity } from '@neogroup/neorm'

import { Profile } from '@/app/_models/types'

@Entity({ table: 'users' })
export class User {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  email!: string

  @Column()
  password_hash!: string | null

  @Column()
  first_name!: string | null

  @Column()
  last_name!: string | null

  @Column()
  nickname!: string | null

  @Column()
  profile!: Profile | null

  @Column({ cast: 'date' })
  created_at!: Date
}

/** Typed facade for the static query methods injected by the @Entity decorator. */
export const UserModel = User as any
