import { BaseEntity, Column, Entity } from '@neogroup/neorm'
import { Discipline } from '@/app/(protected)/(tournaments)/models/Discipline'
import { SubDiscipline } from '@/app/(protected)/(tournaments)/models/SubDiscipline'

/**
 * Catalogue of categories scoped to an organization and a discipline /
 * sub-discipline. Categories are created on demand the first time an organizer
 * uses a given name while creating a tournament, and reused afterwards (which
 * powers the category autocomplete). Tournaments materialise a subset of them
 * into tournament_categories rows; competitors, rounds and matches point to one
 * of those category instances.
 */
@Entity({ table: 'categories' })
export class Category extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  organizationId!: number

  @Column()
  name!: string

  @Column({ cast: 'number' })
  discipline!: Discipline

  /** Sub-discipline (tennis only). Null for padel. */
  @Column()
  subDiscipline!: SubDiscipline | null
}
