import { BaseEntity, BelongsTo, BelongsToThrough, Column, Entity, HasManyInArray, Serializable } from '@neogroup/neorm'
import { Tournament } from '@/app/(protected)/(tournaments)/models/Tournament'
import { TournamentCategory } from '@/app/(protected)/(tournaments)/models/TournamentCategory'
import { User } from '@/app/models/User'
import { getUserDisplayName, getUserShortName } from '@/app/utils/users'

@Entity({ table: 'competitors' })
export class Competitor extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentCategoryId!: number

  /**
   * Users that make up this competitor, in roster order: 1 for singles, 2 for
   * pairs, N for team disciplines. The first id is the main player.
   */
  @Column({ cast: 'array' })
  playerIds!: number[]

  /**
   * Preclassification seed. Before the tournament starts, this is only ever
   * non-null when the organizer set it manually from the admin page; once set
   * that way it takes priority over the ranking-based auto-assignment that
   * runs when the tournament starts (see `autoAssignPreclassification`).
   */
  @Column({ cast: 'number' })
  seedNumber!: number | null

  @Column({ cast: 'date' })
  createdAt!: Date

  @BelongsTo(() => TournamentCategory, 'tournamentCategoryId')
  tournamentCategory?: TournamentCategory

  @BelongsToThrough(() => Tournament, () => TournamentCategory, 'tournamentCategoryId', 'tournamentId')
  tournament?: Tournament

  /** The player users, resolved from `playerIds` (preserving roster order). */
  @HasManyInArray(() => User, 'playerIds')
  players?: User[]

  @Serializable()
  get displayName(): string {
    return (this.players ?? [])
      .map((player) => getUserDisplayName(player))
      .filter(Boolean)
      .join(' / ')
  }

  @Serializable()
  get shortName(): string {
    return (this.players ?? [])
      .map((player) => getUserShortName(player))
      .filter(Boolean)
      .join(' / ')
  }
}
