import { BaseEntity, BelongsTo, BelongsToThrough, Column, Entity } from '@neogroup/neorm'
import { User } from '@/app/(auth)/models/User'
import { Tournament } from '@/app/(protected)/(tournaments)/models/Tournament'
import { TournamentCategory } from '@/app/(protected)/(tournaments)/models/TournamentCategory'

@Entity({ table: 'competitors' })
export class Competitor extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  /** Category instance this entry is registered in (implies the tournament). */
  @Column({ cast: 'number' })
  tournamentCategoryId!: number

  /** Platform user that registered this entry (null when added manually). */
  @Column()
  userId!: number | null

  /** Partner as a platform user (doubles disciplines only). */
  @Column()
  partnerUserId!: number | null

  /** Partner as free text (doubles disciplines only). */
  @Column()
  partnerName!: string | null

  /** Resolved name shown everywhere (player or "Player / Partner"). */
  @Column()
  displayName!: string

  @Column({ cast: 'date' })
  createdAt!: Date

  @BelongsTo(() => TournamentCategory, 'tournamentCategoryId')
  tournamentCategory?: TournamentCategory

  /** Shortcut to the tournament (through tournamentCategory). */
  @BelongsToThrough(() => Tournament, () => TournamentCategory, 'tournamentCategoryId', 'tournamentId')
  tournament?: Tournament

  @BelongsTo(() => User, 'userId')
  user?: User

  @BelongsTo(() => User, 'partnerUserId')
  partnerUser?: User
}
