import { BaseEntity, BelongsTo, BelongsToThrough, Column, Entity } from '@neogroup/neorm'
import { MatchSide } from '@/app/(protected)/(tournaments)/models/MatchSide'
import { MatchStatus } from '@/app/(protected)/(tournaments)/models/MatchStatus'
import { Round } from '@/app/(protected)/(tournaments)/models/Round'
import { Tournament } from '@/app/(protected)/(tournaments)/models/Tournament'
import { TournamentCategory } from '@/app/(protected)/(tournaments)/models/TournamentCategory'

@Entity({ table: 'matches' })
export class Match extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  /** Category instance this match belongs to. */
  @Column({ cast: 'number' })
  tournamentCategoryId!: number

  @Column({ cast: 'number' })
  roundId!: number

  @Column({ cast: 'number' })
  position!: number

  @Column({ cast: 'array' })
  homeCompetitorIds!: number[]

  @Column({ cast: 'array' })
  awayCompetitorIds!: number[] | null

  /**
   * Match score in the compact string format `{scoreFormatId}:{results}` (see
   * utils/score.ts → serializeScore / parseScore). Null when no result yet.
   */
  @Column()
  score!: string | null

  @Column({ cast: 'number' })
  status!: MatchStatus

  @Column()
  winner!: MatchSide | null

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date

  @BelongsTo(() => TournamentCategory, 'tournamentCategoryId')
  tournamentCategory?: TournamentCategory

  /** Shortcut to the tournament (through tournamentCategory). */
  @BelongsToThrough(() => Tournament, () => TournamentCategory, 'tournamentCategoryId', 'tournamentId')
  tournament?: Tournament

  @BelongsTo(() => Round, 'roundId')
  round?: Round
}
