import { BaseEntity, BelongsTo, BelongsToThrough, Column, Entity, HasMany } from '@neogroup/neorm'
import { Match } from '@/app/(protected)/(tournaments)/models/Match'
import { RoundStatus } from '@/app/(protected)/(tournaments)/models/RoundStatus'
import { RoundType } from '@/app/(protected)/(tournaments)/models/RoundType'
import { Tournament } from '@/app/(protected)/(tournaments)/models/Tournament'
import { TournamentCategory } from '@/app/(protected)/(tournaments)/models/TournamentCategory'

/** Optional per-round configuration stored as JSONB. */
export interface RoundSettings {
  groupNumber?: number | null
}

@Entity({ table: 'rounds' })
export class Round extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentCategoryId!: number

  @Column({ cast: 'number' })
  number!: number

  @Column({ cast: 'number' })
  status!: RoundStatus

  @Column({ cast: 'number' })
  type!: RoundType

  @Column({ cast: 'json' })
  settings!: RoundSettings | null

  @Column({ cast: 'boolean' })
  active!: boolean

  @Column({ cast: 'date' })
  createdAt!: Date

  @BelongsTo(() => TournamentCategory, 'tournamentCategoryId')
  tournamentCategory?: TournamentCategory

  @BelongsToThrough(() => Tournament, () => TournamentCategory, 'tournamentCategoryId', 'tournamentId')
  tournament?: Tournament

  @HasMany(() => Match, 'roundId')
  matches?: Match[]

  get groupNumber(): number | null {
    return this.settings?.groupNumber ?? null
  }

  set groupNumber(value: number | null) {
    this.settings = { ...(this.settings ?? {}), groupNumber: value }
  }
}
