import { BaseEntity, BelongsTo, Column, Entity, HasMany } from '@neogroup/neorm'
import { Match } from '@/app/(protected)/(tournaments)/models/Match'
import { RoundStatus } from '@/app/(protected)/(tournaments)/models/RoundStatus'
import { Tournament } from '@/app/(protected)/(tournaments)/models/Tournament'

@Entity({ table: 'rounds' })
export class Round extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentId!: number

  @Column({ cast: 'number' })
  number!: number

  @Column({ cast: 'number' })
  status!: RoundStatus

  /** Category this round belongs to (null when the tournament has none). */
  @Column()
  category!: string | null

  @Column({ cast: 'date' })
  createdAt!: Date

  @BelongsTo(() => Tournament, 'tournamentId')
  tournament?: Tournament

  @HasMany(() => Match, 'roundId')
  matches?: Match[]
}
