import { BaseEntity, BelongsTo, Column, Entity, HasMany, HasManyThrough } from '@neogroup/neorm'
import { User } from '@/app/(auth)/models/User'
import { Competitor } from '@/app/(protected)/(tournaments)/models/Competitor'
import { Discipline } from '@/app/(protected)/(tournaments)/models/Discipline'
import { Match } from '@/app/(protected)/(tournaments)/models/Match'
import { Round } from '@/app/(protected)/(tournaments)/models/Round'
import { ScoreFormat } from '@/app/(protected)/(tournaments)/models/ScoreFormat'
import { SubDiscipline } from '@/app/(protected)/(tournaments)/models/SubDiscipline'
import { TournamentCategory } from '@/app/(protected)/(tournaments)/models/TournamentCategory'
import { TournamentSettings } from '@/app/(protected)/(tournaments)/models/TournamentSettings'
import { TournamentStatus } from '@/app/(protected)/(tournaments)/models/TournamentStatus'
import { TournamentType } from '@/app/(protected)/(tournaments)/models/TournamentType'

@Entity({ table: 'tournaments' })
export class Tournament extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  organizationId!: number

  @Column({ cast: 'number' })
  ownerId!: number

  @Column()
  name!: string

  @Column()
  description!: string | null

  @Column({ cast: 'number' })
  status!: TournamentStatus

  @Column({ cast: 'number' })
  discipline!: Discipline

  /** Sub-discipline (tennis only: singles or doubles). Null for padel. */
  @Column()
  subDiscipline!: SubDiscipline | null

  @Column({ cast: 'number' })
  type!: TournamentType

  @Column({ cast: 'number' })
  scoreFormat!: ScoreFormat

  /** Calendar start date as a "YYYY-MM-DD" string (no time/timezone component). */
  @Column()
  startDate!: string

  /** Optional start time in "HH:mm" format. */
  @Column()
  startTime!: string | null

  @Column()
  location!: string | null

  @Column({ cast: 'json' })
  settings!: TournamentSettings | null

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date

  @BelongsTo(() => User, 'ownerId')
  owner?: User

  /**
   * Concrete category instances of the tournament (always at least one). When
   * the tournament has no organizer-defined categories this is a single row
   * with categoryId = null (the "single category").
   */
  @HasMany(() => TournamentCategory, 'tournamentId')
  categories?: TournamentCategory[]

  /** Competitors across every category, reached through tournament_categories. */
  @HasManyThrough(() => Competitor, () => TournamentCategory, 'tournamentCategoryId', 'tournamentId')
  competitors?: Competitor[]

  /** Rounds across every category, reached through tournament_categories. */
  @HasManyThrough(() => Round, () => TournamentCategory, 'tournamentCategoryId', 'tournamentId')
  rounds?: Round[]

  /** Matches across every category, reached through tournament_categories. */
  @HasManyThrough(() => Match, () => TournamentCategory, 'tournamentCategoryId', 'tournamentId')
  matches?: Match[]
}
