import { BaseEntity, BelongsTo, Column, Entity, HasMany } from '@neogroup/neorm'
import { Category } from '@/app/(protected)/(tournaments)/models/Category'
import { Competitor } from '@/app/(protected)/(tournaments)/models/Competitor'
import { Round } from '@/app/(protected)/(tournaments)/models/Round'
import { Tournament } from '@/app/(protected)/(tournaments)/models/Tournament'

/**
 * Concrete category instance of a tournament. A tournament always has at least
 * one: when the organizer defines categories there is one row per category
 * (categoryId set); when it has none there is a single row with categoryId =
 * null (rendered as the "single category" in the UI). maxCompetitors is the
 * entry limit of this instance.
 */
@Entity({ table: 'tournament_categories' })
export class TournamentCategory extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentId!: number

  /** Catalogue category this instance maps to. Null for the single category. */
  @Column()
  categoryId!: number | null

  @Column({ cast: 'number' })
  maxCompetitors!: number

  @BelongsTo(() => Tournament, 'tournamentId')
  tournament?: Tournament

  /** Resolved catalogue category (null for the single category). */
  @BelongsTo(() => Category, 'categoryId')
  category?: Category | null

  @HasMany(() => Competitor, 'tournamentCategoryId')
  competitors?: Competitor[]

  @HasMany(() => Round, 'tournamentCategoryId')
  rounds?: Round[]
}
