import { BaseEntity, BelongsTo, Column, Entity, HasMany, HasManyThrough, HasOne } from '@neogroup/neorm'
import { RankingSettings } from '@/app/(protected)/(rankings)/models/RankingSettings'
import { Site } from '@/app/(protected)/(sites)/models/Site'
import { Competitor } from '@/app/(protected)/(tournaments)/models/Competitor'
import { Discipline } from '@/app/(protected)/(tournaments)/models/Discipline'
import { Match } from '@/app/(protected)/(tournaments)/models/Match'
import { ScoreFormat } from '@/app/(protected)/(tournaments)/models/ScoreFormat'
import { SubDiscipline } from '@/app/(protected)/(tournaments)/models/SubDiscipline'
import { TournamentCategory } from '@/app/(protected)/(tournaments)/models/TournamentCategory'
import { TournamentImage } from '@/app/(protected)/(tournaments)/models/TournamentImage'
import { TournamentSettings } from '@/app/(protected)/(tournaments)/models/TournamentSettings'
import { TournamentStatus } from '@/app/(protected)/(tournaments)/models/TournamentStatus'
import { TournamentType } from '@/app/(protected)/(tournaments)/models/TournamentType'
import { OrganizationScope } from '@/app/models/OrganizationScope'
import { User } from '@/app/models/User'

@Entity({ table: 'tournaments' })
export class Tournament extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  organizationId!: number

  @Column({ cast: 'number' })
  ownerId!: number

  @Column()
  name!: string

  @Column()
  description!: string | null

  @Column({ cast: 'number' })
  status!: TournamentStatus

  @Column({ cast: 'number' })
  discipline!: Discipline

  @Column()
  subDiscipline!: SubDiscipline | null

  @Column({ cast: 'number' })
  type!: TournamentType

  @Column({ cast: 'number' })
  scoreFormat!: ScoreFormat

  @Column()
  startDate!: string

  @Column()
  startTime!: string | null

  /**
   * Optional "YYYY-MM-DD" date from which the tournament accepts registrations.
   * Null means registrations are open since the tournament was created.
   */
  @Column()
  startInscriptionsDate!: string | null

  /** Venue where the tournament is played (catalogue managed by the administrator). */
  @Column()
  siteId!: number | null

  @Column({ cast: 'json' })
  settings!: TournamentSettings | null

  @Column({ cast: 'json' })
  rankingSettings!: RankingSettings | null

  /**
   * Whether TeamUp's service fee for this tournament has already been settled by
   * the organization (see the "Pagos" module). It says nothing about whether the
   * tournament has a cost for players — that is `entryFee > 0`. Free tournaments
   * are never billed, so they stay `false` forever.
   */
  @Column({ cast: 'boolean' })
  paid!: boolean

  /** When the service fee was settled. Null while `paid` is false. */
  @Column({ cast: 'date' })
  paidAt!: Date | null

  /** Settlement that paid this tournament's service fee. Null while unpaid. */
  @Column({ cast: 'number' })
  servicePaymentId!: number | null

  /**
   * Entry fee players pay to take part, settled directly with the organizer
   * (cash at the venue, transfer, …) — never through the platform. Null/0 means
   * the tournament is free, and it is also the base TeamUp's service fee is
   * computed on.
   */
  @Column({ cast: 'number' })
  entryFee!: number | null

  /** ISO currency code of the entry fee (e.g. "ARS"). */
  @Column()
  currency!: string

  /** When true, a player taking part in a match may submit its result themselves. Otherwise only the organizer can. */
  @Column({ cast: 'boolean' })
  allowPlayerSetScore!: boolean

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date

  @BelongsTo(() => User, 'ownerId')
  owner?: User

  @BelongsTo(() => Site, 'siteId')
  site?: Site | null

  @HasMany(() => TournamentCategory, 'tournamentId')
  categories?: TournamentCategory[]

  @HasOne(() => TournamentImage, 'tournamentId')
  image?: TournamentImage | null

  @HasManyThrough(() => Competitor, () => TournamentCategory, 'tournamentCategoryId', 'tournamentId')
  competitors?: Competitor[]

  @HasManyThrough(() => Match, () => TournamentCategory, 'tournamentCategoryId', 'tournamentId')
  matches?: Match[]

  protected static booted(): void {
    Tournament.addGlobalScope(new OrganizationScope())
  }
}
