import { BaseEntity, BelongsTo, Column, Entity, HasMany } from '@neogroup/neorm'
import { Category } from '@/app/(protected)/(categories)/models/Category'
import { Competitor } from '@/app/(protected)/(tournaments)/models/Competitor'
import { Match } from '@/app/(protected)/(tournaments)/models/Match'
import { Tournament } from '@/app/(protected)/(tournaments)/models/Tournament'

/**
 * Concrete category instance of a tournament. A tournament always has at least
 * one: when the organizer defines categories there is one row per category
 * (categoryId set); when it has none there is a single row with categoryId =
 * null (rendered as the "single category" in the UI). maxCompetitors is the
 * entry limit of this instance.
 */
@Entity({ table: 'tournament_categories' })
export class TournamentCategory extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentId!: number

  @Column()
  categoryId!: number | null

  @Column({ cast: 'number' })
  maxCompetitors!: number

  /**
   * Winner of this category, materialised when the tournament finishes (see
   * `finishTournament`). Null while it is still running, and also for a
   * finished category whose final never got a result.
   *
   * It exists so counting a player's titles is an indexed COUNT instead of
   * replaying the whole bracket: the champion can only change while the
   * tournament is ONGOING — `setMatchResult` refuses a result on anything else
   * — so once written it never moves.
   */
  @Column({ cast: 'number' })
  championCompetitorId!: number | null

  @BelongsTo(() => Tournament, 'tournamentId')
  tournament?: Tournament

  @BelongsTo(() => Category, 'categoryId')
  category?: Category | null

  @HasMany(() => Competitor, 'tournamentCategoryId')
  competitors?: Competitor[]

  @HasMany(() => Match, 'tournamentCategoryId')
  matches?: Match[]
}
