import { BaseEntity, BelongsTo, Column, Entity } from '@neogroup/neorm'
import { Competitor } from '@/app/(protected)/(tournaments)/models/Competitor'
import { PaymentStatus } from '@/app/(protected)/(tournaments)/models/PaymentStatus'
import { Tournament } from '@/app/(protected)/(tournaments)/models/Tournament'
import { TournamentCategory } from '@/app/(protected)/(tournaments)/models/TournamentCategory'

/**
 * Registration payment for a paid tournament. Created (status PENDING) when a
 * player starts the checkout; it snapshots the intended entry and the money
 * split at that moment. When Mercado Pago confirms the payment the status
 * becomes APPROVED and the competitor is created (linked via competitorId).
 *
 * No organization global scope is added on purpose: the Mercado Pago webhook
 * resolves payments without a subdomain/organization context.
 */
@Entity({ table: 'tournament_payments' })
export class TournamentPayment extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  organizationId!: number

  @Column({ cast: 'number' })
  tournamentId!: number

  @Column({ cast: 'number' })
  tournamentCategoryId!: number

  /** Roster of players this payment registers (payer is playerIds[0]). */
  @Column({ cast: 'array' })
  playerIds!: number[]

  @Column({ cast: 'number' })
  status!: PaymentStatus

  /** Total amount paid by the player. */
  @Column({ cast: 'number' })
  amount!: number

  @Column()
  currency!: string

  /** Service fee percentage applied (snapshot of the organization value at creation). */
  @Column({ cast: 'number' })
  serviceFeePercentage!: number

  /** Portion of `amount` collected by TeamUp (marketplace_fee). */
  @Column({ cast: 'number' })
  serviceFeeAmount!: number

  /** Portion of `amount` settled to the organizer (amount − serviceFeeAmount). */
  @Column({ cast: 'number' })
  organizerAmount!: number

  @Column()
  provider!: string

  /** Mercado Pago Checkout Pro preference id. */
  @Column()
  preferenceId!: string | null

  /** Mercado Pago payment id (set once a payment exists for the preference). */
  @Column()
  mpPaymentId!: string | null

  /** Checkout URL the player is redirected to. */
  @Column()
  initPoint!: string | null

  /** Competitor created once the payment is approved. */
  @Column({ cast: 'number' })
  competitorId!: number | null

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date

  @BelongsTo(() => Tournament, 'tournamentId')
  tournament?: Tournament

  @BelongsTo(() => TournamentCategory, 'tournamentCategoryId')
  tournamentCategory?: TournamentCategory

  @BelongsTo(() => Competitor, 'competitorId')
  competitor?: Competitor
}
