import { BelongsTo, Column, Entity } from '@neogroup/neorm'
import { MatchScore } from '@/app/(tournaments)/models/MatchScore'
import { MatchSide } from '@/app/(tournaments)/models/MatchSide'
import { MatchStatus } from '@/app/(tournaments)/models/MatchStatus'
import { Round } from '@/app/(tournaments)/models/Round'
import { Tournament } from '@/app/(tournaments)/models/Tournament'

@Entity({ table: 'matches' })
export class Match {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentId!: number

  @Column({ cast: 'number' })
  roundId!: number

  /** Ordering inside the round; also encodes the playoff bracket slot. */
  @Column({ cast: 'number' })
  position!: number

  /**
   * Competitor ids on each side. A side holds a single id except in
   * americano tournaments with partner swapping, where two individual
   * competitors team up per round. `awayCompetitorIds` is null for byes.
   */
  @Column({ cast: 'json' })
  homeCompetitorIds!: number[]

  @Column({ cast: 'json' })
  awayCompetitorIds!: number[] | null

  @Column({ cast: 'json' })
  score!: MatchScore | null

  @Column({ cast: 'number' })
  status!: MatchStatus

  @Column()
  winner!: MatchSide | null

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date

  @BelongsTo(() => Tournament, 'tournamentId')
  tournament?: Tournament

  @BelongsTo(() => Round, 'roundId')
  round?: Round

  /** Rebuilds a Match instance from its JSON representation. */
  static fromJSON(json: Record<string, any>): Match {
    const match = Object.setPrototypeOf(json, Match.prototype) as Match

    if (typeof json.createdAt === 'string') {
      match.createdAt = new Date(json.createdAt)
    }

    if (typeof json.updatedAt === 'string') {
      match.updatedAt = new Date(json.updatedAt)
    }

    return match
  }
}

