import { BaseEntity, BelongsTo, Column, Dto, Entity, HasMany } from '@neogroup/neorm'
import { Match } from '@/app/(tournaments)/models/Match'
import { RoundStatus } from '@/app/(tournaments)/models/RoundStatus'
import { Tournament } from '@/app/(tournaments)/models/Tournament'

@Entity({ table: 'rounds' })
export class Round extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentId!: number

  @Column({ cast: 'number' })
  number!: number

  @Column({ cast: 'number' })
  status!: RoundStatus

  @Column({ cast: 'date' })
  createdAt!: Date

  @BelongsTo(() => Tournament, 'tournamentId')
  tournament?: Tournament

  @HasMany(() => Match, 'roundId')
  matches?: Match[]
}

/** Plain serializable round passed from server code to client components. */
export type RoundDto = Dto<Round>
