import { BelongsTo, Column, Entity, HasMany } from '@neogroup/neorm'
import { Match } from '@/app/(tournaments)/models/Match'
import { RoundStatus } from '@/app/(tournaments)/models/RoundStatus'
import { Tournament } from '@/app/(tournaments)/models/Tournament'

@Entity({ table: 'rounds' })
export class Round {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentId!: number

  @Column({ cast: 'number' })
  number!: number

  @Column({ cast: 'number' })
  status!: RoundStatus

  /** Category this round belongs to (null when the tournament has none). */
  @Column()
  category!: string | null

  @Column({ cast: 'date' })
  createdAt!: Date

  @BelongsTo(() => Tournament, 'tournamentId')
  tournament?: Tournament

  @HasMany(() => Match, 'roundId')
  matches?: Match[]

  /** Rebuilds a Round instance from its JSON representation. */
  static fromJSON(json: Record<string, any>): Round {
    const round = Object.setPrototypeOf(json, Round.prototype) as Round

    if (typeof json.createdAt === 'string') {
      round.createdAt = new Date(json.createdAt)
    }

    return round
  }
}

