import { BaseEntity, BelongsTo, Column, Entity, HasMany } from '@neogroup/neorm'
import { User } from '@/app/(auth)/models/User'
import { Competitor } from '@/app/(tournaments)/models/Competitor'
import { Discipline } from '@/app/(tournaments)/models/Discipline'
import { Match } from '@/app/(tournaments)/models/Match'
import { Round } from '@/app/(tournaments)/models/Round'
import { ScoreFormat } from '@/app/(tournaments)/models/ScoreFormat'
import { SubDiscipline } from '@/app/(tournaments)/models/SubDiscipline'
import { TournamentSettings } from '@/app/(tournaments)/models/TournamentSettings'
import { TournamentStatus } from '@/app/(tournaments)/models/TournamentStatus'
import { TournamentType } from '@/app/(tournaments)/models/TournamentType'

@Entity({ table: 'tournaments' })
export class Tournament extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  ownerId!: number

  @Column()
  name!: string

  @Column()
  description!: string | null

  @Column({ cast: 'number' })
  status!: TournamentStatus

  @Column({ cast: 'number' })
  discipline!: Discipline

  /** Sub-discipline (tennis only: singles or doubles). Null for padel. */
  @Column()
  subDiscipline!: SubDiscipline | null

  @Column({ cast: 'number' })
  type!: TournamentType

  @Column({ cast: 'number' })
  scoreFormat!: ScoreFormat

  /** Calendar start date as a "YYYY-MM-DD" string (no time/timezone component). */
  @Column()
  startDate!: string

  /** Optional start time in "HH:mm" format. */
  @Column()
  startTime!: string | null

  @Column()
  location!: string | null

  /** Optional free-text category names defined by the organizer. */
  @Column({ cast: 'json' })
  categories!: string[] | null

  @Column({ cast: 'number' })
  maxCompetitors!: number

  @Column({ cast: 'json' })
  settings!: TournamentSettings | null

  @Column({ cast: 'number' })
  currentRound!: number

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date

  @BelongsTo(() => User, 'ownerId')
  owner?: User

  @HasMany(() => Competitor, 'tournamentId')
  competitors?: Competitor[]

  @HasMany(() => Round, 'tournamentId')
  rounds?: Round[]

  @HasMany(() => Match, 'tournamentId')
  matches?: Match[]
}
