import { BelongsTo, Column, Entity, HasMany } from '@neogroup/neorm'
import { User } from '@/app/(auth)/models/User'
import { Competitor } from '@/app/(tournaments)/models/Competitor'
import { Discipline } from '@/app/(tournaments)/models/Discipline'
import { Match } from '@/app/(tournaments)/models/Match'
import { Round } from '@/app/(tournaments)/models/Round'
import { ScoreFormat } from '@/app/(tournaments)/models/ScoreFormat'
import { SubDiscipline } from '@/app/(tournaments)/models/SubDiscipline'
import { TournamentSettings } from '@/app/(tournaments)/models/TournamentSettings'
import { TournamentStatus } from '@/app/(tournaments)/models/TournamentStatus'
import { TournamentType } from '@/app/(tournaments)/models/TournamentType'

@Entity({ table: 'tournaments' })
export class Tournament {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  ownerId!: number

  @Column()
  name!: string

  @Column()
  description!: string | null

  @Column({ cast: 'number' })
  status!: TournamentStatus

  @Column({ cast: 'number' })
  discipline!: Discipline

  /** Sub-discipline (tennis only: singles or doubles). Null for padel. */
  @Column()
  subDiscipline!: SubDiscipline | null

  @Column({ cast: 'number' })
  type!: TournamentType

  @Column({ cast: 'number' })
  scoreFormat!: ScoreFormat

  @Column()
  startDate!: string

  @Column()
  location!: string | null

  @Column({ cast: 'number' })
  maxCompetitors!: number

  @Column({ cast: 'json' })
  settings!: TournamentSettings | null

  @Column({ cast: 'number' })
  currentRound!: number

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date

  /** Organizer that owns this tournament. */
  @BelongsTo(() => User, 'ownerId')
  owner?: User

  @HasMany(() => Competitor, 'tournamentId')
  competitors?: Competitor[]

  @HasMany(() => Round, 'tournamentId')
  rounds?: Round[]

  @HasMany(() => Match, 'tournamentId')
  matches?: Match[]

  /** Computed count of registered competitors (not stored in DB). */
  competitorsCount?: number
}
