import { BelongsTo, Column, Entity, HasMany } from '@neogroup/neorm'
import { User } from '@/app/(auth)/models/User'
import { Competitor } from '@/app/(tournaments)/models/Competitor'
import { Discipline } from '@/app/(tournaments)/models/Discipline'
import { Match } from '@/app/(tournaments)/models/Match'
import { Round } from '@/app/(tournaments)/models/Round'
import { ScoreFormat } from '@/app/(tournaments)/models/ScoreFormat'
import { SubDiscipline } from '@/app/(tournaments)/models/SubDiscipline'
import { TournamentSettings } from '@/app/(tournaments)/models/TournamentSettings'
import { TournamentStatus } from '@/app/(tournaments)/models/TournamentStatus'
import { TournamentType } from '@/app/(tournaments)/models/TournamentType'

@Entity({ table: 'tournaments' })
export class Tournament {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  ownerId!: number

  @Column()
  name!: string

  @Column()
  description!: string | null

  @Column({ cast: 'number' })
  status!: TournamentStatus

  @Column({ cast: 'number' })
  discipline!: Discipline

  /** Sub-discipline (tennis only: singles or doubles). Null for padel. */
  @Column()
  subDiscipline!: SubDiscipline | null

  @Column({ cast: 'number' })
  type!: TournamentType

  @Column({ cast: 'number' })
  scoreFormat!: ScoreFormat

  @Column({ cast: 'date' })
  startDate!: Date

  @Column()
  location!: string | null

  @Column({ cast: 'number' })
  maxCompetitors!: number

  @Column({ cast: 'json' })
  settings!: TournamentSettings | null

  @Column({ cast: 'number' })
  currentRound!: number

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date

  /** Organizer that owns this tournament. */
  @BelongsTo(() => User, 'ownerId')
  owner?: User

  @HasMany(() => Competitor, 'tournamentId')
  competitors?: Competitor[]

  @HasMany(() => Round, 'tournamentId')
  rounds?: Round[]

  @HasMany(() => Match, 'tournamentId')
  matches?: Match[]

  /** Computed from loaded competitors relation. */
  get competitorsCount(): number {
    return this.competitors?.length ?? 0
  }

  /**
   * Custom JSON serialization: strips loaded relations (they are returned
   * separately in API responses), formats dates as YYYY-MM-DD strings, and
   * includes computed getters so they survive JSON.stringify.
   */
  toJSON(): Record<string, any> {
    const result: Record<string, any> = {}

    for (const key of Object.keys(this as any)) {
      // Skip relation properties — returned separately by the API
      if (key === 'owner' || key === 'competitors' || key === 'rounds' || key === 'matches') {
        continue
      }

      const value = (this as any)[key]

      result[key] = value instanceof Date ? value.toISOString().slice(0, 10) : value
    }

    result.competitorsCount = this.competitorsCount

    return result
  }
}
