import { BaseEntity, Column, Entity } from '@neogroup/neorm'
import { OrganizationScope } from '@/app/models/OrganizationScope'

/**
 * Venue of an organization ("sede"). Maintained by the administrator in the
 * /sites ABM and picked — never typed — when creating or editing a tournament,
 * which points at it through `tournaments.siteId`.
 *
 * It replaces the old free-text `tournaments.location`, where the same club
 * ended up spelled in as many ways as organizers there were (see migration
 * 008-sites).
 */
@Entity({ table: 'sites' })
export class Site extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  organizationId!: number

  @Column()
  name!: string

  protected static booted(): void {
    Site.addGlobalScope(new OrganizationScope())
  }
}
