import { BaseEntity, Column, Entity } from '@neogroup/neorm'
import { SiteData } from '@/app/(protected)/(sites)/models/SiteData'
import { OrganizationScope } from '@/app/models/OrganizationScope'

/**
 * Venue of an organization ("sede"). Maintained by the administrator in the
 * /sites ABM and picked — never typed — when creating or editing a tournament,
 * which points at it through `tournaments.siteId`.
 *
 * It replaces the old free-text `tournaments.location`, where the same club
 * ended up spelled in as many ways as organizers there were (see migration
 * 008-sites).
 */
@Entity({ table: 'sites' })
export class Site extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  organizationId!: number

  @Column()
  name!: string

  /**
   * Settings of the venue — its courts setup, and the duration it was last
   * planned with. Written by the organizer's planner, read by everyone who
   * looks at a schedule (see SiteData and migration 019-sites-data). Null on a
   * venue nobody has planned yet.
   */
  @Column({ cast: 'json' })
  data!: SiteData | null

  protected static booted(): void {
    Site.addGlobalScope(new OrganizationScope())
  }
}
