import { BaseEntity, Column, Entity, HasMany } from '@neogroup/neorm'
import { Role } from '@/app/(auth)/models/Role'
import { getUserDisplayName } from '@/app/(auth)/utils/user'
import { getGravatarUrl } from '@/app/utils/gravatar'

@Entity({ table: 'users' })
export class User extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  email!: string

  @Column()
  passwordHash!: string | null

  @Column()
  firstName!: string | null

  @Column()
  lastName!: string | null

  @Column()
  nickname!: string | null

  /** Role of the user: 1 = organizer, 2 = player. Assigned once, cannot be switched. */
  @Column()
  roleId!: Role | null

  @Column({ cast: 'date' })
  createdAt!: Date

  get displayName(): string {
    return getUserDisplayName(this)
  }

  get avatarUrl(): string {
    return getGravatarUrl(this.email, 80)
  }

  toJSON(): Record<string, any> {
    const result: Record<string, any> = {}

    for (const key of Object.keys(this as any)) {
      if (key === 'passwordHash') continue
      const value = (this as any)[key]
      result[key] = value instanceof Date ? value.toISOString() : value
    }

    result.displayName = this.displayName
    result.avatarUrl = this.avatarUrl

    return result
  }
}
