import { BaseEntity, Column, Entity } from '@neogroup/neorm'
import { Profile } from '@/app/(auth)/models/user'

@Entity({ table: 'users' })
export class User extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  email!: string

  @Column()
  passwordHash!: string | null

  @Column()
  firstName!: string | null

  @Column()
  lastName!: string | null

  @Column()
  nickname!: string | null

  @Column()
  profile!: Profile | null

  @Column({ cast: 'date' })
  createdAt!: Date
}
