import { BaseEntity, BelongsTo, Column, Entity } from '@neogroup/neorm'
import { MatchScore } from '@/app/(tournaments)/models/MatchScore'
import { MatchSide } from '@/app/(tournaments)/models/MatchSide'
import { MatchStatus } from '@/app/(tournaments)/models/MatchStatus'
import { Round } from '@/app/(tournaments)/entities/Round'
import { Tournament } from '@/app/(tournaments)/entities/Tournament'

@Entity({ table: 'matches' })
export class Match extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentId!: number

  @Column({ cast: 'number' })
  roundId!: number

  @Column({ cast: 'number' })
  position!: number

  @Column({ cast: 'json' })
  homeCompetitorIds!: number[]

  @Column({ cast: 'json' })
  awayCompetitorIds!: number[] | null

  @Column({ cast: 'json' })
  score!: MatchScore | null

  @Column({ cast: 'number' })
  status!: MatchStatus

  @Column()
  winner!: MatchSide | null

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date

  @BelongsTo(() => Tournament, 'tournamentId')
  tournament?: Tournament

  @BelongsTo(() => Round, 'roundId')
  round?: Round
}
