import { BaseEntity, Column, Entity } from '@neogroup/neorm'
import { MatchScore, MatchSide, MatchStatus } from '@/app/(tournaments)/models/types'

@Entity({ table: 'matches' })
export class Match extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentId!: number

  @Column({ cast: 'number' })
  roundId!: number

  /** Ordering inside the round; also encodes the playoff bracket slot. */
  @Column({ cast: 'number' })
  position!: number

  /**
   * Competitor ids on each side. A side holds a single id except in
   * americano tournaments with partner swapping, where two individual
   * competitors team up per round. `awayCompetitorIds` is null for byes.
   */
  @Column({ cast: 'json' })
  homeCompetitorIds!: number[]

  @Column({ cast: 'json' })
  awayCompetitorIds!: number[] | null

  @Column({ cast: 'json' })
  score!: MatchScore | null

  @Column()
  status!: MatchStatus

  @Column()
  winner!: MatchSide | null

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date
}
