import { BaseEntity, BelongsTo, Column, Entity, HasMany } from '@neogroup/neorm'
import { Match } from '@/app/(tournaments)/entities/Match'
import { Tournament } from '@/app/(tournaments)/entities/Tournament'
import { RoundStatus } from '@/app/(tournaments)/models/types'

@Entity({ table: 'rounds' })
export class Round extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tournamentId!: number

  @Column({ cast: 'number' })
  number!: number

  @Column()
  status!: RoundStatus

  @Column({ cast: 'date' })
  createdAt!: Date

  @BelongsTo(() => Tournament, 'tournamentId')
  tournament?: Tournament

  @HasMany(() => Match, 'roundId')
  matches?: Match[]
}
