import { BaseEntity, BelongsTo, Column, Entity, HasMany } from '@neogroup/neorm'
import { User } from '@/app/(auth)/entities/User'
import { Competitor } from '@/app/(tournaments)/entities/Competitor'
import { Match } from '@/app/(tournaments)/entities/Match'
import { Round } from '@/app/(tournaments)/entities/Round'
import {
  Discipline,
  ScoreFormat,
  TournamentSettings,
  TournamentStatus,
  TournamentType
} from '@/app/(tournaments)/models/types'

@Entity({ table: 'tournaments' })
export class Tournament extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  ownerId!: number

  @Column()
  name!: string

  @Column()
  description!: string | null

  @Column()
  status!: TournamentStatus

  @Column()
  discipline!: Discipline

  @Column()
  type!: TournamentType

  @Column()
  scoreFormat!: ScoreFormat

  @Column()
  startDate!: string

  @Column()
  location!: string | null

  @Column({ cast: 'number' })
  maxCompetitors!: number

  @Column({ cast: 'json' })
  settings!: TournamentSettings | null

  @Column({ cast: 'number' })
  currentRound!: number

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date

  /** Organizer that owns this tournament. */
  @BelongsTo(() => User, 'ownerId')
  owner?: User

  @HasMany(() => Competitor, 'tournamentId')
  competitors?: Competitor[]

  @HasMany(() => Round, 'tournamentId')
  rounds?: Round[]

  @HasMany(() => Match, 'tournamentId')
  matches?: Match[]
}
