import { BaseEntity, Column, Entity } from '@neogroup/neorm'

/**
 * Cached, pre-computed organization-wide stats backing the organizer home
 * dashboard. There is at most one row per organization. The dashboard service
 * refreshes it lazily: at most once every 24h, or sooner if any match in the
 * organization has been edited since `updatedAt`.
 */
@Entity({ table: 'organization_statistics' })
export class OrganizationStatistics extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  organizationId!: number

  @Column({ cast: 'number' })
  tournamentsTotal!: number

  @Column({ cast: 'number' })
  tournamentsActive!: number

  @Column({ cast: 'number' })
  tournamentsFinished!: number

  @Column({ cast: 'number' })
  competitorsTotal!: number

  @Column({ cast: 'number' })
  avgCompetitors!: number

  @Column({ cast: 'number' })
  distinctPlayers!: number

  @Column({ cast: 'number' })
  matchesTotal!: number

  @Column({ cast: 'number' })
  matchesPlayed!: number

  @Column({ cast: 'number' })
  matchesPending!: number

  @Column({ cast: 'number' })
  rankingPointsAwarded!: number

  @Column({ cast: 'number' })
  rankedPlayers!: number

  @Column({ cast: 'date' })
  updatedAt!: Date
}
