import { BaseEntity, Column, Entity } from '@neogroup/neorm'

/**
 * Cached, pre-computed per-player stats backing the player home dashboard.
 * There is at most one row per player (user). The dashboard service refreshes
 * it lazily: at most once every 24h, or sooner if one of the player's matches
 * has been edited since `updatedAt`.
 */
@Entity({ table: 'player_statistics' })
export class PlayerStatistics extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  playerId!: number

  @Column({ cast: 'number' })
  tournamentsPlayed!: number

  @Column({ cast: 'number' })
  activeTournaments!: number

  @Column({ cast: 'number' })
  matchesPlayed!: number

  @Column({ cast: 'number' })
  matchesWon!: number

  @Column({ cast: 'number' })
  winRate!: number

  @Column({ cast: 'number' })
  titles!: number

  @Column({ cast: 'number' })
  podiums!: number

  @Column({ cast: 'number' })
  rankingPoints!: number

  @Column({ cast: 'number' })
  bestRankingPosition!: number

  @Column({ cast: 'date' })
  updatedAt!: Date
}
