import { BaseEntity, BelongsTo, Column, Entity } from '@neogroup/neorm'
import { User } from '@/app/models/User'

/**
 * Mercado Pago account that a tournament organizer connects via OAuth so the
 * platform can create split payments on their behalf.
 *
 * SECURITY: this entity holds sensitive OAuth credentials (accessToken /
 * refreshToken). It lives in its own table and must NEVER be eager-loaded
 * together with a User that is serialized to the client (e.g. getUsers), so the
 * tokens are never exposed through a UserDto. Only server-side payment code
 * reads these columns.
 */
@Entity({ table: 'mercadopago_accounts' })
export class MercadoPagoAccount extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  userId!: number

  /** Mercado Pago account id (the seller "user_id" returned by the OAuth token endpoint). */
  @Column()
  mpUserId!: string

  @Column()
  accessToken!: string

  @Column()
  refreshToken!: string | null

  @Column()
  publicKey!: string | null

  @Column({ cast: 'boolean' })
  liveMode!: boolean | null

  @Column()
  scope!: string | null

  /** When the access token expires; used to refresh it proactively. */
  @Column({ cast: 'date' })
  expiresAt!: Date | null

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date

  @BelongsTo(() => User, 'userId')
  user?: User
}
