import { BaseEntity, Column, Entity } from '@neogroup/neorm'

@Entity({ table: 'organizations' })
export class Organization extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  /** Subdomain slug used to identify the organization (e.g. "club-aleman"). */
  @Column()
  domainName!: string

  /**
   * Roles allowed to self-register through the platform.
   * Empty array means no self-registration is allowed — all users must be created manually.
   * E.g. [Role.PLAYER] allows only players; [Role.PLAYER, Role.ORGANIZER] allows both.
   */
  @Column({ cast: 'array' })
  allowedRegistrationRoles!: number[]

  /**
   * Disciplines (see app/(protected)/(tournaments)/models/Discipline.ts) the
   * organization offers. Every screen that lists disciplines — category and
   * tournament forms, ranking filters — only shows the ones in this array.
   * Defaults to every discipline that exists today (padel and tennis).
   */
  @Column({ cast: 'array' })
  enabledDisciplines!: number[]

  /**
   * IANA timezone of the organization (e.g. "America/Argentina/Buenos_Aires").
   * Used to interpret a tournament's startDate/startTime so the processTournaments
   * cron starts each tournament at the organization's local scheduled time.
   */
  @Column()
  timezone!: string

  /**
   * Platform service fee, as a percentage of the entry fees a tournament
   * collected, that this organization owes TeamUp (e.g. 4 = 4%). It is billed
   * per tournament over the competitors that played at least one match, and
   * settled from the "Pagos" page. Configured per organization (not editable by
   * organizers — it is TeamUp's cut).
   */
  @Column({ cast: 'number' })
  serviceFeePercentage!: number

  @Column({ cast: 'date' })
  createdAt!: Date
}
