import { BaseEntity, Column, Entity, Serializable } from '@neogroup/neorm'
import { OrganizationScope } from '@/app/models/OrganizationScope'
import { Role } from '@/app/models/Role'
import { getGravatarUrl } from '@/app/utils/gravatar'
import { getUserDisplayName, getUserShortName } from '@/app/utils/users'

@Entity({ table: 'users' })
export class User extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  organizationId!: number

  @Column()
  email!: string

  @Column()
  passwordHash!: string | null

  @Column()
  firstName!: string | null

  @Column()
  lastName!: string | null

  @Column()
  nickname!: string | null

  @Column()
  phoneNumber!: string | null

  /** Role of the user: 1 = administrator, 2 = organizer, 3 = player. Assigned once, cannot be switched. */
  @Column()
  roleId!: Role | null

  /** True when the user verified their email address. Always true for Google-authenticated users. */
  @Column({ cast: 'boolean' })
  emailVerified!: boolean

  /** False disables the account's login. Toggled by an Administrator to ban/unban a user. */
  @Column({ cast: 'boolean' })
  active!: boolean

  @Column({ cast: 'date' })
  createdAt!: Date

  @Serializable()
  get displayName(): string {
    return getUserDisplayName(this)
  }

  @Serializable()
  get shortName(): string {
    return getUserShortName(this)
  }

  @Serializable()
  get avatarUrl(): string {
    return getGravatarUrl(this.email, 80)
  }

  protected static booted(): void {
    User.addGlobalScope(new OrganizationScope())
    User.addGlobalScope('activeScope', (query) => {
      query.where('active', true)
    })
    User.addGlobalScope('emailVerifiedScope', (query) => {
      query.where('emailVerified', true)
    })
  }
}
