import { BaseEntity, BelongsTo, Column, Entity } from '@neogroup/neorm'
import { Category } from '@/app/(protected)/(tournaments)/models/Category'
import { OrganizationScope } from '@/app/models/OrganizationScope'
import { User } from '@/app/models/User'

/**
 * A single ranking award granted to a player when a tournament finishes. Each
 * row is worth `points` for the player in the catalogue category, valid until
 * `expirationDate` (one year after it is granted). The rankings browser sums
 * the still-valid rows per player and category.
 */
@Entity({ table: 'rankings' })
export class Ranking extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  organizationId!: number

  @Column({ cast: 'number' })
  categoryId!: number

  @Column({ cast: 'number' })
  userId!: number

  @Column({ cast: 'number' })
  points!: number

  @Column({ cast: 'date' })
  expirationDate!: Date

  @Column({ cast: 'date' })
  createdAt!: Date

  @BelongsTo(() => Category, 'categoryId')
  category?: Category

  @BelongsTo(() => User, 'userId')
  user?: User

  protected static booted(): void {
    Ranking.addGlobalScope(new OrganizationScope())
    Ranking.addGlobalScope('expirationScope', (query) => {
      query.where('expirationDate', '>', new Date())
    })
  }
}
