import { BaseEntity, BelongsTo, Column, Entity } from '@neogroup/neorm'
import { User } from '@/app/(auth)/models/User'
import { Category } from '@/app/(protected)/(tournaments)/models/Category'

/**
 * A single ranking award granted to a player when a tournament finishes. Each
 * row is worth `points` for the player in the catalogue category, valid until
 * `expirationDate` (one year after it is granted). The rankings browser sums
 * the still-valid rows per player and category.
 */
@Entity({ table: 'rankings' })
export class Ranking extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  organizationId!: number

  /** Catalogue category this award belongs to. */
  @Column({ cast: 'number' })
  categoryId!: number

  /** Player that earned the award. */
  @Column({ cast: 'number' })
  userId!: number

  @Column({ cast: 'number' })
  points!: number

  /** Moment the award stops counting towards the ranking (granted + 1 year). */
  @Column({ cast: 'date' })
  expirationDate!: Date

  @Column({ cast: 'date' })
  createdAt!: Date

  @BelongsTo(() => Category, 'categoryId')
  category?: Category

  @BelongsTo(() => User, 'userId')
  user?: User
}
