import { BaseEntity, Column, Entity } from '@neogroup/neorm'
import { PaymentStatus } from '@/app/(protected)/(payments)/models/PaymentStatus'

/**
 * A settlement of TeamUp's service fee: the organization paying for the
 * tournaments of theirs that already took place.
 *
 * One row is created (status PENDING) when an organizer or administrator starts
 * the checkout from the "Pagos" page, and it **snapshots** what is being
 * charged — which tournaments, how many billable competitors and the resulting
 * amount — so a registration or a match played after the checkout started
 * cannot retroactively change the price. When Mercado Pago confirms the payment
 * the status becomes APPROVED and every tournament in `tournamentIds` is marked
 * as paid.
 *
 * No organization global scope is added on purpose: the Mercado Pago webhook
 * resolves the settlement without a subdomain/organization context.
 */
@Entity({ table: 'service_payments' })
export class ServicePayment extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  organizationId!: number

  /** User that started the checkout (the organizer or the administrator). */
  @Column({ cast: 'number' })
  userId!: number

  /** Tournaments this settlement covers, snapshotted when the checkout started. */
  @Column({ cast: 'array' })
  tournamentIds!: number[]

  /** Total billable competitors across `tournamentIds` (those that played at least one match). */
  @Column({ cast: 'number' })
  competitorsCount!: number

  /** Sum of `billableCompetitors × entryFee` of every covered tournament. */
  @Column({ cast: 'number' })
  grossAmount!: number

  /** Service fee percentage applied (snapshot of the organization value at creation). */
  @Column({ cast: 'number' })
  serviceFeePercentage!: number

  /** What is actually charged: `grossAmount × serviceFeePercentage %`. */
  @Column({ cast: 'number' })
  amount!: number

  @Column()
  currency!: string

  @Column({ cast: 'number' })
  status!: PaymentStatus

  @Column()
  provider!: string

  /** Mercado Pago Checkout Pro preference id. */
  @Column()
  preferenceId!: string | null

  /** Mercado Pago payment id (set once a payment exists for the preference). */
  @Column()
  mpPaymentId!: string | null

  /** Checkout URL the payer is redirected to. */
  @Column()
  initPoint!: string | null

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  updatedAt!: Date
}
